# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'program.ui'
#
# Created: Fri Mar 24 09:37:15 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(887, 587)
        MainWindow.setMinimumSize(QtCore.QSize(887, 587))
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.framesearch = QtGui.QFrame(self.centralwidget)
        self.framesearch.setFrameShape(QtGui.QFrame.NoFrame)
        self.framesearch.setFrameShadow(QtGui.QFrame.Raised)
        self.framesearch.setObjectName(_fromUtf8("framesearch"))
        self.gridLayout = QtGui.QGridLayout(self.framesearch)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.IDMAX = QtGui.QSpinBox(self.framesearch)
        self.IDMAX.setAccelerated(True)
        self.IDMAX.setMinimum(1)
        self.IDMAX.setMaximum(252)
        self.IDMAX.setSingleStep(1)
        self.IDMAX.setObjectName(_fromUtf8("IDMAX"))
        self.horizontalLayout.addWidget(self.IDMAX)
        self.label_5 = QtGui.QLabel(self.framesearch)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.IDMIN = QtGui.QSpinBox(self.framesearch)
        self.IDMIN.setAccelerated(True)
        self.IDMIN.setMinimum(1)
        self.IDMIN.setMaximum(252)
        self.IDMIN.setObjectName(_fromUtf8("IDMIN"))
        self.horizontalLayout.addWidget(self.IDMIN)
        self.label_4 = QtGui.QLabel(self.framesearch)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.portttxt = QtGui.QLabel(self.framesearch)
        self.portttxt.setObjectName(_fromUtf8("portttxt"))
        self.gridLayout.addWidget(self.portttxt, 1, 0, 1, 1)
        self.portcombox = QtGui.QComboBox(self.framesearch)
        self.portcombox.setObjectName(_fromUtf8("portcombox"))
        self.portcombox.addItem(_fromUtf8(""))
        self.portcombox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.portcombox, 2, 0, 1, 1)
        self.BAUDRATEtxt = QtGui.QLabel(self.framesearch)
        self.BAUDRATEtxt.setObjectName(_fromUtf8("BAUDRATEtxt"))
        self.gridLayout.addWidget(self.BAUDRATEtxt, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.scanbutton = QtGui.QPushButton(self.framesearch)
        self.scanbutton.setMinimumSize(QtCore.QSize(266, 27))
        self.scanbutton.setMaximumSize(QtCore.QSize(266, 27))
        self.scanbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scanbutton.setStyleSheet(_fromUtf8("background-image: url(:/testebutton.jpg);"))
        self.scanbutton.setObjectName(_fromUtf8("scanbutton"))
        self.horizontalLayout_5.addWidget(self.scanbutton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.Baudratelist = QtGui.QListWidget(self.framesearch)
        self.Baudratelist.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Baudratelist.setFrameShadow(QtGui.QFrame.Sunken)
        self.Baudratelist.setLineWidth(0)
        self.Baudratelist.setMidLineWidth(0)
        self.Baudratelist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Baudratelist.setDragEnabled(False)
        self.Baudratelist.setDragDropOverwriteMode(False)
        self.Baudratelist.setMovement(QtGui.QListView.Static)
        self.Baudratelist.setFlow(QtGui.QListView.TopToBottom)
        self.Baudratelist.setViewMode(QtGui.QListView.ListMode)
        self.Baudratelist.setUniformItemSizes(False)
        self.Baudratelist.setWordWrap(False)
        self.Baudratelist.setObjectName(_fromUtf8("Baudratelist"))
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.Baudratelist.addItem(item)
        self.gridLayout.addWidget(self.Baudratelist, 4, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.searchparamtxt = QtGui.QLabel(self.framesearch)
        self.searchparamtxt.setObjectName(_fromUtf8("searchparamtxt"))
        self.horizontalLayout_8.addWidget(self.searchparamtxt)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.framesearch, 0, 0, 1, 1)
        self.framelist = QtGui.QFrame(self.centralwidget)
        self.framelist.setFrameShape(QtGui.QFrame.NoFrame)
        self.framelist.setFrameShadow(QtGui.QFrame.Raised)
        self.framelist.setObjectName(_fromUtf8("framelist"))
        self.gridLayout_2 = QtGui.QGridLayout(self.framelist)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.framelist)
        self.label_6.setEnabled(True)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.listWidget = QtGui.QListWidget(self.framelist)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setFrameShape(QtGui.QFrame.Panel)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_2.addWidget(self.listWidget, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.framelist, 0, 1, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frameconfig = QtGui.QFrame(self.centralwidget)
        self.frameconfig.setMaximumSize(QtCore.QSize(273, 523))
        self.frameconfig.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameconfig.setFrameShadow(QtGui.QFrame.Raised)
        self.frameconfig.setObjectName(_fromUtf8("frameconfig"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frameconfig)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.modellist = QtGui.QComboBox(self.frameconfig)
        self.modellist.setObjectName(_fromUtf8("modellist"))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.modellist.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.modellist, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.torquemaxtxt = QtGui.QLabel(self.frameconfig)
        self.torquemaxtxt.setObjectName(_fromUtf8("torquemaxtxt"))
        self.horizontalLayout_2.addWidget(self.torquemaxtxt)
        self.torqueslider = QtGui.QSlider(self.frameconfig)
        self.torqueslider.setMinimum(1)
        self.torqueslider.setMaximum(100)
        self.torqueslider.setProperty("value", 100)
        self.torqueslider.setTracking(True)
        self.torqueslider.setOrientation(QtCore.Qt.Horizontal)
        self.torqueslider.setObjectName(_fromUtf8("torqueslider"))
        self.horizontalLayout_2.addWidget(self.torqueslider)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spinBox = QtGui.QSpinBox(self.frameconfig)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 100)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.label = QtGui.QLabel(self.frameconfig)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.reversemode_2 = QtGui.QCheckBox(self.frameconfig)
        self.reversemode_2.setEnabled(False)
        self.reversemode_2.setObjectName(_fromUtf8("reversemode_2"))
        self.horizontalLayout_7.addWidget(self.reversemode_2)
        self.slavemode_2 = QtGui.QCheckBox(self.frameconfig)
        self.slavemode_2.setEnabled(False)
        self.slavemode_2.setObjectName(_fromUtf8("slavemode_2"))
        self.horizontalLayout_7.addWidget(self.slavemode_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 8, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.frameconfig)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.servoidtxt = QtGui.QLabel(self.frameconfig)
        self.servoidtxt.setObjectName(_fromUtf8("servoidtxt"))
        self.verticalLayout.addWidget(self.servoidtxt)
        self.servoid = QtGui.QSpinBox(self.frameconfig)
        self.servoid.setAccelerated(True)
        self.servoid.setMinimum(1)
        self.servoid.setMaximum(252)
        self.servoid.setObjectName(_fromUtf8("servoid"))
        self.verticalLayout.addWidget(self.servoid)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.servobaudrate = QtGui.QLabel(self.frameconfig)
        self.servobaudrate.setObjectName(_fromUtf8("servobaudrate"))
        self.verticalLayout_2.addWidget(self.servobaudrate)
        self.servobaudlist = QtGui.QComboBox(self.frameconfig)
        self.servobaudlist.setObjectName(_fromUtf8("servobaudlist"))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.servobaudlist.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.servobaudlist)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 2)
        self.checkBox = QtGui.QCheckBox(self.frameconfig)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 1, 0, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.newidtxt = QtGui.QLabel(self.frameconfig)
        self.newidtxt.setObjectName(_fromUtf8("newidtxt"))
        self.verticalLayout_3.addWidget(self.newidtxt)
        self.newid = QtGui.QSpinBox(self.frameconfig)
        self.newid.setAccelerated(True)
        self.newid.setMinimum(1)
        self.newid.setMaximum(252)
        self.newid.setObjectName(_fromUtf8("newid"))
        self.verticalLayout_3.addWidget(self.newid)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.newbaud = QtGui.QLabel(self.frameconfig)
        self.newbaud.setObjectName(_fromUtf8("newbaud"))
        self.verticalLayout_4.addWidget(self.newbaud)
        self.newbaudlist = QtGui.QComboBox(self.frameconfig)
        self.newbaudlist.setObjectName(_fromUtf8("newbaudlist"))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.newbaudlist.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.newbaudlist)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.updatememory = QtGui.QPushButton(self.frameconfig)
        self.updatememory.setMaximumSize(QtCore.QSize(1920, 1080))
        self.updatememory.setStyleSheet(_fromUtf8("background-image: url(:/updateeprombut.jpg);"))
        self.updatememory.setFlat(False)
        self.updatememory.setObjectName(_fromUtf8("updatememory"))
        self.gridLayout_7.addWidget(self.updatememory, 9, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_16 = QtGui.QLabel(self.frameconfig)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.wheel_2 = QtGui.QCheckBox(self.frameconfig)
        self.wheel_2.setStyleSheet(_fromUtf8("background-image: url(:/background.jpg);"))
        self.wheel_2.setObjectName(_fromUtf8("wheel_2"))
        self.horizontalLayout_6.addWidget(self.wheel_2)
        self.joint_2 = QtGui.QCheckBox(self.frameconfig)
        self.joint_2.setAutoFillBackground(False)
        self.joint_2.setCheckable(True)
        self.joint_2.setTristate(False)
        self.joint_2.setObjectName(_fromUtf8("joint_2"))
        self.horizontalLayout_6.addWidget(self.joint_2)
        self.multiturn_2 = QtGui.QCheckBox(self.frameconfig)
        self.multiturn_2.setEnabled(False)
        self.multiturn_2.setObjectName(_fromUtf8("multiturn_2"))
        self.horizontalLayout_6.addWidget(self.multiturn_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_13 = QtGui.QLabel(self.frameconfig)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_6.addWidget(self.label_13)
        self.cwanglelimit = QtGui.QSpinBox(self.frameconfig)
        self.cwanglelimit.setEnabled(False)
        self.cwanglelimit.setFrame(True)
        self.cwanglelimit.setAccelerated(True)
        self.cwanglelimit.setKeyboardTracking(True)
        self.cwanglelimit.setSuffix(_fromUtf8(""))
        self.cwanglelimit.setMaximum(4095)
        self.cwanglelimit.setObjectName(_fromUtf8("cwanglelimit"))
        self.verticalLayout_6.addWidget(self.cwanglelimit)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_14 = QtGui.QLabel(self.frameconfig)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_5.addWidget(self.label_14)
        self.ccwanglelimit = QtGui.QSpinBox(self.frameconfig)
        self.ccwanglelimit.setEnabled(False)
        self.ccwanglelimit.setAccelerated(True)
        self.ccwanglelimit.setMaximum(4095)
        self.ccwanglelimit.setObjectName(_fromUtf8("ccwanglelimit"))
        self.verticalLayout_5.addWidget(self.ccwanglelimit)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 6, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frameconfig)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.frameconfig)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_8 = QtGui.QLabel(self.frameconfig)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.frameconfig)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.Dgain = QtGui.QSpinBox(self.frameconfig)
        self.Dgain.setAccelerated(True)
        self.Dgain.setMaximum(254)
        self.Dgain.setObjectName(_fromUtf8("Dgain"))
        self.horizontalLayout_9.addWidget(self.Dgain)
        self.Igain = QtGui.QSpinBox(self.frameconfig)
        self.Igain.setAccelerated(True)
        self.Igain.setMaximum(254)
        self.Igain.setObjectName(_fromUtf8("Igain"))
        self.horizontalLayout_9.addWidget(self.Igain)
        self.pgain = QtGui.QSpinBox(self.frameconfig)
        self.pgain.setAccelerated(True)
        self.pgain.setMaximum(254)
        self.pgain.setProperty("value", 10)
        self.pgain.setObjectName(_fromUtf8("pgain"))
        self.horizontalLayout_9.addWidget(self.pgain)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.gridLayout_7.addLayout(self.verticalLayout_8, 7, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frameconfig)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Baudratelist.setCurrentRow(-1)
        QtCore.QObject.connect(self.torqueslider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBox.setValue)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.torqueslider.setValue)
        QtCore.QObject.connect(self.joint_2, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.ccwanglelimit.setEnabled)
        QtCore.QObject.connect(self.joint_2, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cwanglelimit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.modellist.currentIndexChanged.connect(self.enable_checkboxes)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_5.setText(_translate("MainWindow", "Max. ID", None))
        self.label_4.setText(_translate("MainWindow", "Min. ID", None))
        self.portttxt.setText(_translate("MainWindow", "PORTS", None))
        self.portcombox.setItemText(0, _translate("MainWindow", "/dev/ttyUSB0", None))
        self.portcombox.setItemText(1, _translate("MainWindow", "/dev/ttyUSB1", None))
        self.BAUDRATEtxt.setText(_translate("MainWindow", "BAUDRATES", None))
        self.scanbutton.setText(_translate("MainWindow", "SCAN", None))
        self.Baudratelist.setSortingEnabled(False)
        __sortingEnabled = self.Baudratelist.isSortingEnabled()
        self.Baudratelist.setSortingEnabled(False)
        item = self.Baudratelist.item(0)
        item.setText(_translate("MainWindow", "1000000", None))
        item = self.Baudratelist.item(1)
        item.setText(_translate("MainWindow", "500000", None))
        item = self.Baudratelist.item(2)
        item.setText(_translate("MainWindow", "400000", None))
        item = self.Baudratelist.item(3)
        item.setText(_translate("MainWindow", "250000", None))
        item = self.Baudratelist.item(4)
        item.setText(_translate("MainWindow", "200000", None))
        item = self.Baudratelist.item(5)
        item.setText(_translate("MainWindow", "115200", None))
        item = self.Baudratelist.item(6)
        item.setText(_translate("MainWindow", "57600", None))
        item = self.Baudratelist.item(7)
        item.setText(_translate("MainWindow", "19200", None))
        item = self.Baudratelist.item(8)
        item.setText(_translate("MainWindow", "9600", None))
        self.Baudratelist.setSortingEnabled(__sortingEnabled)
        self.searchparamtxt.setText(_translate("MainWindow", "SEARCH PARAMETERS", None))
        self.label_6.setText(_translate("MainWindow", "Motors Found", None))
        self.modellist.setItemText(0, _translate("MainWindow", "AX-12W", None))
        self.modellist.setItemText(1, _translate("MainWindow", "AX-12A", None))
        self.modellist.setItemText(2, _translate("MainWindow", "AX-18", None))
        self.modellist.setItemText(3, _translate("MainWindow", "EX-106+ ", None))
        self.modellist.setItemText(4, _translate("MainWindow", "RX-24F ", None))
        self.modellist.setItemText(5, _translate("MainWindow", "RX-28 ", None))
        self.modellist.setItemText(6, _translate("MainWindow", "RX-64 ", None))
        self.modellist.setItemText(7, _translate("MainWindow", "MX-12W ", None))
        self.modellist.setItemText(8, _translate("MainWindow", "MX-28", None))
        self.modellist.setItemText(9, _translate("MainWindow", "MX-64", None))
        self.modellist.setItemText(10, _translate("MainWindow", "MX-106drive", None))
        self.modellist.setItemText(11, _translate("MainWindow", "MX1062.0 NON SUPORTED", None))
        self.modellist.setItemText(12, _translate("MainWindow", "MX-28 2.0 NON SUPORTED", None))
        self.modellist.setItemText(13, _translate("MainWindow", "MX-64 2.0 NON SUPORTED", None))
        self.torquemaxtxt.setText(_translate("MainWindow", "Torque Max", None))
        self.label.setText(_translate("MainWindow", "%", None))
        self.reversemode_2.setText(_translate("MainWindow", "Reverse Mode", None))
        self.slavemode_2.setText(_translate("MainWindow", "Slave Mode", None))
        self.label_7.setText(_translate("MainWindow", "Configuration Parameters", None))
        self.servoidtxt.setText(_translate("MainWindow", "Servo ID", None))
        self.servobaudrate.setText(_translate("MainWindow", "Servo Baudrate", None))
        self.servobaudlist.setItemText(0, _translate("MainWindow", "1000000", None))
        self.servobaudlist.setItemText(1, _translate("MainWindow", "500000", None))
        self.servobaudlist.setItemText(2, _translate("MainWindow", "400000", None))
        self.servobaudlist.setItemText(3, _translate("MainWindow", "250000", None))
        self.servobaudlist.setItemText(4, _translate("MainWindow", "200000", None))
        self.servobaudlist.setItemText(5, _translate("MainWindow", "11520", None))
        self.servobaudlist.setItemText(6, _translate("MainWindow", "57600", None))
        self.servobaudlist.setItemText(7, _translate("MainWindow", "19200", None))
        self.servobaudlist.setItemText(8, _translate("MainWindow", "9600", None))
        self.checkBox.setText(_translate("MainWindow", "Factory Reset", None))
        self.newidtxt.setText(_translate("MainWindow", "New ID", None))
        self.newbaud.setText(_translate("MainWindow", "New Baudrate", None))
        self.newbaudlist.setItemText(0, _translate("MainWindow", "1000000", None))
        self.newbaudlist.setItemText(1, _translate("MainWindow", "500000", None))
        self.newbaudlist.setItemText(2, _translate("MainWindow", "400000", None))
        self.newbaudlist.setItemText(3, _translate("MainWindow", "250000", None))
        self.newbaudlist.setItemText(4, _translate("MainWindow", "200000", None))
        self.newbaudlist.setItemText(5, _translate("MainWindow", "11520", None))
        self.newbaudlist.setItemText(6, _translate("MainWindow", "57600", None))
        self.newbaudlist.setItemText(7, _translate("MainWindow", "19200", None))
        self.newbaudlist.setItemText(8, _translate("MainWindow", "9600", None))
        self.updatememory.setText(_translate("MainWindow", "UPDATE MEMORY", None))
        self.label_16.setText(_translate("MainWindow", "Mode set", None))
        self.wheel_2.setText(_translate("MainWindow", "Wheel", None))
        self.joint_2.setText(_translate("MainWindow", "Joint", None))
        self.multiturn_2.setText(_translate("MainWindow", "Multi Turn", None))
        self.label_13.setText(_translate("MainWindow", "CW ANGLE LIMIT", None))
        self.label_14.setText(_translate("MainWindow", "CCW ANGLE LIMIT", None))
        self.label_2.setText(_translate("MainWindow", "Model", None))
        self.label_3.setText(_translate("MainWindow", "D Gain", None))
        self.label_8.setText(_translate("MainWindow", "I Gain", None))
        self.label_9.setText(_translate("MainWindow", "P Gain", None))
        

    def enable_checkboxes(self):
        multiturn_servos_index = [7,8,9]
        if self.modellist.currentIndex() in multiturn_servos_index:
            self.multiturn_2.setEnabled(True)
        
        
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

